function build_simple_model()
%BUILD_SIMPLE_MODEL 构建简化版ACC决策+SPPVT模型
%   创建最基本的可工作模型，避免复杂功能导致的错误

fprintf('🚀 开始构建简化版ACC决策+SPPVT模型...\n');

%% 1. 创建新模型
model_name = 'ACC_Decision_SPPVT_Simple';

% 检查并清理现有模型
if bdIsLoaded(model_name)
    fprintf('⚠️ 关闭现有模型...\n');
    close_system(model_name, 0);
end

if exist([model_name '.slx'], 'file')
    fprintf('🗑️ 删除现有模型文件...\n');
    delete([model_name '.slx']);
end

% 创建新模型
fprintf('📄 创建新模型: %s\n', model_name);
new_system(model_name);
open_system(model_name);

%% 2. 确保总线定义存在
fprintf('🔧 检查总线定义...\n');
if ~evalin('base', 'exist(''DecisionSPPVTInput'', ''var'')') || ...
   ~evalin('base', 'exist(''DecisionSPPVTOutput'', ''var'')')
    fprintf('⚠️ 创建总线定义...\n');
    create_decision_sppvt_bus();
else
    fprintf('✅ 总线定义已存在\n');
end

%% 3. 基本模型配置
fprintf('⚙️ 配置模型参数...\n');
set_param(model_name, 'SolverType', 'Fixed-step');
set_param(model_name, 'FixedStep', '0.05');
set_param(model_name, 'StartTime', '0.0');
set_param(model_name, 'StopTime', '10.0');

%% 4. 创建输入端口
fprintf('📥 创建输入端口...\n');
input_port = add_block('simulink/Sources/In1', [model_name '/Input'], ...
    'Position', [50, 100, 100, 130]);
set_param(input_port, 'OutDataTypeStr', 'Bus: DecisionSPPVTInput');

%% 5. 创建MATLAB Function块 - 集成决策和SPPVT
fprintf('🧠 创建集成处理模块...\n');
matlab_fcn = add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [model_name '/Integrated_Function'], 'Position', [300, 80, 500, 150]);

% 设置MATLAB Function代码 (MATLAB 2024b兼容方式)
try
    integrated_code = generate_integrated_function_code();
    
    % 方法1: 尝试直接设置Script参数
    set_param(matlab_fcn, 'Script', integrated_code);
    
catch ME1
    try
        % 方法2: 使用Simulink.MATLABFunctionConfiguration
        mfConfig = Simulink.MATLABFunctionConfiguration(matlab_fcn);
        mfConfig.FunctionScript = integrated_code;
        
    catch ME2
        % 方法3: 手动设置（需要用户手动编辑）
        fprintf('⚠️ 无法自动设置MATLAB Function代码\n');
        fprintf('💡 请手动双击Integrated_Function块，复制以下代码:\n');
        fprintf('==================代码开始==================\n');
        fprintf('%s\n', integrated_code);
        fprintf('==================代码结束==================\n');
    end
end

%% 6. 创建输出端口
fprintf('📤 创建输出端口...\n');
output_port = add_block('simulink/Sinks/Out1', [model_name '/Output'], ...
    'Position', [700, 100, 750, 130]);
set_param(output_port, 'OutDataTypeStr', 'Bus: DecisionSPPVTOutput');

%% 7. 连接模块
fprintf('🔗 连接模块...\n');
try
    add_line(model_name, 'Input/1', 'Integrated_Function/1');
    add_line(model_name, 'Integrated_Function/1', 'Output/1');
    fprintf('✅ 模块连接成功\n');
catch ME
    fprintf('⚠️ 连接警告: %s\n', ME.message);
end

%% 8. 保存模型
fprintf('💾 保存模型...\n');
try
    save_system(model_name);
    fprintf('✅ 模型已保存: %s.slx\n', model_name);
catch ME
    fprintf('⚠️ 保存警告: %s\n', ME.message);
end

fprintf('🎉 简化模型构建完成!\n');
fprintf('📁 模型文件: %s.slx\n', model_name);
fprintf('🔧 使用方法: open_system(''%s'')\n', model_name);

end

function code = generate_integrated_function_code()
%GENERATE_INTEGRATED_FUNCTION_CODE 生成集成的MATLAB Function代码

code = [
'function output = fcn(input)', newline, ...
'%#codegen', newline, ...
'% ACC决策+SPPVT一体化处理函数', newline, ...
'% 简化版本 - 集成决策逻辑和SPPVT控制', newline, newline, ...
'%% 初始化persistent变量', newline, ...
'persistent current_state integral_term prev_error', newline, ...
'if isempty(current_state)', newline, ...
'    current_state = int32(0);  % S0: 待命状态', newline, ...
'    integral_term = 0.0;', newline, ...
'    prev_error = 0.0;', newline, ...
'end', newline, newline, ...
'%% 提取输入参数', newline, ...
'ego_speed_kmh = input.ego_speed_kmh;', newline, ...
'command_type = input.command_type;', newline, ...
'command_active = input.command_active;', newline, ...
'control_error = input.control_error;', newline, ...
'manual_throttle_active = input.manual_throttle_active;', newline, newline, ...
'%% 决策逻辑 (简化)', newline, ...
'control_enabled = false;', newline, ...
'torque_arbitration_active = false;', newline, newline, ...
'if command_active', newline, ...
'    switch command_type', newline, ...
'        case 1  % I0: 当速启控', newline, ...
'            if ego_speed_kmh >= 30', newline, ...
'                current_state = int32(1);  % 转到主动控制', newline, ...
'                control_enabled = true;', newline, ...
'            end', newline, ...
'        case 2  % I1: 增速启控', newline, ...
'            if ego_speed_kmh >= 30', newline, ...
'                current_state = int32(1);', newline, ...
'                control_enabled = true;', newline, ...
'            end', newline, ...
'        case 5  % I4: 油门指令', newline, ...
'            if manual_throttle_active', newline, ...
'                current_state = int32(3);  % 扭矩仲裁状态', newline, ...
'                control_enabled = true;', newline, ...
'                torque_arbitration_active = true;', newline, ...
'            end', newline, ...
'        case 7  % I6: 取消', newline, ...
'            current_state = int32(0);  % 回到待命', newline, ...
'            control_enabled = false;', newline, ...
'    end', newline, ...
'end', newline, newline, ...
'%% SPPVT控制 (简化)', newline, ...
'target_accel = 0.0;', newline, newline, ...
'if control_enabled && abs(control_error) > 0.1', newline, ...
'    % PID控制参数', newline, ...
'    kp = 0.8;', newline, ...
'    ki = 0.1;', newline, ...
'    kd = 0.05;', newline, ...
'    dt = 0.05;', newline, newline, ...
'    % PID计算', newline, ...
'    P_term = kp * control_error;', newline, ...
'    integral_term = integral_term + control_error * dt;', newline, ...
'    integral_term = max(-5, min(5, integral_term));  % 积分限幅', newline, ...
'    I_term = ki * integral_term;', newline, ...
'    D_term = kd * (control_error - prev_error) / dt;', newline, newline, ...
'    target_accel = P_term + I_term + D_term;', newline, ...
'    target_accel = max(-4.0, min(2.0, target_accel));  % 限幅', newline, newline, ...
'    prev_error = control_error;', newline, ...
'end', newline, newline, ...
'%% 构造输出', newline, ...
'output = struct();', newline, ...
'output.target_accel = target_accel;', newline, ...
'output.control_enabled = control_enabled;', newline, ...
'output.current_state = current_state;', newline, ...
'output.current_decision = command_type;', newline, ...
'output.torque_arbitration_active = torque_arbitration_active;', newline, ...
'output.updated_V_target_kmh = input.V_target_kmh;', newline, ...
'output.updated_G2_s = input.G2_s;', newline, ...
'output.sppvt_stage = int32(1);', newline, ...
'output.sppvt_upgrade_count = int32(0);', newline, ...
'output.debug_message = int32(1000 + current_state);', newline, ...
'end'
];

end